---
title: "benchmark"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Benchmark

### Just open and close the device

```{r}
#| label: bench1

library(ggplot2)

file <- tempfile(fileext = '.png')

res <- bench::mark(
  wgpugd = {
    wgpugd::wgpugd(file, 10, 10)
    dev.off()
  },
  ragg =  {
    ragg::agg_png(file, 10, 10, unit = "in")
    dev.off()
  },
  min_iterations = 30
)

res

autoplot(res)
```


### Actual plotting

```{r}
#| label: bench2

set.seed(10)
dsamp <- diamonds[sample(nrow(diamonds), 1000), ]

p <- ggplot(dsamp, aes(carat, price)) +
  geom_point(aes(colour = clarity))

res <- bench::mark(
  wgpugd = {
    wgpugd::wgpugd(file, 10, 10)
    print(p)
    dev.off()
  },
  ragg =  {
    ragg::agg_png(file, 10, 10, unit = "in")
    print(p)
    dev.off()
  },
  min_iterations = 30
)

res

autoplot(res)
```

### Multiple plotting

```{r}
#| label: bench3

set.seed(10)
dsamp <- diamonds[sample(nrow(diamonds), 1000), ]

p <- ggplot(dsamp, aes(carat, price)) +
  geom_point(aes(colour = clarity))

temp_dir <- tempfile()
dir.create(temp_dir)
file <- file.path(temp_dir, "p%03d.png")

res <- bench::mark(
  wgpugd = {
    wgpugd::wgpugd(file, 10, 10)
    for (i in 1:20) {
      print(p)
    }
    dev.off()
  },
  ragg =  {
    ragg::agg_png(file, 10, 10, unit = "in")
    for (i in 1:20) {
      print(p)
    }
    dev.off()
  },
  min_iterations = 10
)

res

autoplot(res)
```
