# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_wgpugd_wrappers", use_symbols = TRUE, package_name = "wgpugd")

#' @docType package
#' @usage NULL
#' @useDynLib wgpugd, .registration = TRUE
NULL

#' A WebGPU Graphics Device for R
#'
#' @param filename
#' @param width  Device width in inch.
#' @param height Device width in inch.
#' @export
wgpugd <- function(filename = 'Rplot%03d.png', width = 7, height = 7) invisible(.Call(wrap__wgpugd, filename, width, height))

