# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_wgpugd_wrappers", use_symbols = TRUE, package_name = "wgpugd")

#' @docType package
#' @usage NULL
#' @useDynLib wgpugd, .registration = TRUE
NULL

#' A graphic device that does nothing
#'
#' @param filename
#' @param width  Device width in inch.
#' @param height Device width in inch.
#' @export
wgpugd <- function(filename, width, height) invisible(.Call(wrap__wgpugd, filename, width, height))

